- name: Install Zsh
  ansible.builtin.package:
    name: zsh
    state: present
  when: "'/bin/zsh' in users | map(attribute='shell') | list"

- name: Check if Oh My Zsh is installed
  ansible.builtin.stat:
    path: "/home/{{ item.name }}/.oh-my-zsh"
  register: ohmyzsh_installed
  loop: "{{ users }}"
  when: item.shell == "/bin/zsh"

- name: Install Oh My Zsh
  ansible.builtin.shell: >
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" --unattended
  args:
    creates: "/home/{{ item.name }}/.oh-my-zsh"
  become: yes
  become_user: "{{ item.name }}"
  loop: "{{ users }}"
  when:
    - item.shell == "/bin/zsh"
    - ohmyzsh_installed.results is defined
    - ohmyzsh_installed.results | selectattr('item.name', 'equalto', item.name) | map(attribute='stat.exists') | list | first | default(false) == false
